spring:
  jpa:
    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 20
        default_batch_fetch_size: 20

    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:restaurantvoting
    username: sa
    password:

  jackson:
    visibility.field: any
    visibility.getter: none
    visibility.setter: none
    visibility.is-getter: none

  mvc:
    format:
      date: iso

  cache:
    cache-names: restaurants, dishes
    caffeine.spec: maximumSize=50,expireAfterAccess=60s

logging:
  level:
    root: WARN
    com.github.artemgrishin322.restaurantvoting: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG

server.servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
